config/routes.rb
RefactorDemo::Application.routes.draw do
  resources :posts, except: [:edit] do
    resources :comments, except: [:index, :edit, :update]
  end

  root 'posts#index'

  get '/trash' => 'main_pages#trash', as: :trash

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to  :post,
              inverse_of: :comments
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many  :comments,
            dependent: :destroy,
            inverse_of: :post

  default_scope { where(deleted: false) }

  def destroy
    self.deleted = true
    self.save!
    self.comments.destroy_all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :destroy]
  before_action :set_post

  def create
    @comment = @post.comments.new(comment_params)
    if @comment.save
      redirect_to @post
    else
      render action: 'new'
    end
  end

  def new
    @comment = @post.comments.new
  end

  def show
  end

  def destroy
    @comment.destroy
    redirect_to comments_url
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/main_pages_controller.rb
class MainPagesController < ApplicationController

  def trash
    @posts = Post.where(deleted: true)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :destroy]

  def index
    @posts = Post.all
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to action: 'index'
    else
      render action: 'new'
    end
  end

  def new
    @post = Post.new
  end

  def show
  end

  def update
    set_unscoped_post
    if @post.update(post_params)
      redirect_to @post
    else
      render action: 'index'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def set_unscoped_post
    @post = Post.unscoped.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :deleted)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title= "Comment posted #{time_ago_in_words(comment.created_at)} ago"
  .panel-body
    %p= comment.body

app/views/comments/new.html.haml
= simple_form_for([@post, @comment]) do |form|
  = form.input :body
  = form.button :submit

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title RefactorDemo
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %h1= link_to('Overused Example Blog', root_path)
    = link_to('New Post', new_post_path)
    %hr

    = yield

    %hr
    = link_to('Deleted posts', trash_path)

app/views/main_pages/trash.html.haml
- @posts.each do |post|
  = post.title
  = simple_form_for(post) do |form|
    = form.input :deleted
    = form.button :submit

app/views/posts/_post.html.haml
%article
  %header
    %h3= link_to(post.title, post)
    = link_to('Comment', new_post_comment_path(post))
  %p= post.body
  = link_to('Delete post', post, method: :delete)

app/views/posts/index.html.haml
= render @posts

app/views/posts/new.html.haml
= simple_form_for(@post) do |form|
  = form.input :title
  = form.input :body
  = form.button :submit

app/views/posts/show.html.haml
= render @post
= render @post.comments